algorithm_settings:
  discount_factor: 0.9
  theta: 1e-6

evaluation_metrics:
  runs: 5
  thresholds:
    small: 500     # Threshold for small mazes
    medium: 1000   # Threshold for medium mazes
    large: 2000    # Threshold for large mazes

file_paths:
  maze_file: 'data/mazes/generated_maze.txt'
  solution_path_file: 'data/mazes/solution_path.txt'
